### ISSUE TITLE
link button bug ?

### ISSUE THREAD

**Issue by lingwangyan** [rveachkc/pymsteams#12]
![image](https://user-images.githubusercontent.com/37393953/38853694-9a760572-4250-11e8-8ea4-301dff4890d3.png)

`myTeamsMessage.title("System Alert")
        myTeamsMessage.text("Description: Network error !!")
        myTeamsMessage.addLinkButton("Assign to me", "https://github.com/rveachkc/pymsteams/")
        myTeamsMessage.send()`

when i keep sending same message ... y the button will keep increase ?

**Comment by rveachkc** [comment]
As is, that is the expected behavior.
https://github.com/rveachkc/pymsteams/blob/master/pymsteams/__init__.py#L90

```python
	def addLinkButton(self, buttontext, buttonurl):
		if "potentialAction" not in self.payload:
			self.payload["potentialAction"] = []

		thisbutton = {
			"@context" : "http://schema.org",
			"@type" : "ViewAction",
			"name" : buttontext,
			"target" : [ buttonurl ]
		}

		self.payload["potentialAction"].append(thisbutton)
```

You initialize the object, which has the hookurl attribute and an empty dictionary for the others.
Each time you set the title, you are changing the title attribute, but each time you add a link button, you are appending to the link buttons list.

With the code as is, you can try re-initializing the object for each message to get a blank object.  This is probably the best option:

```
myTeamsMessage = pymsteams.connectorcard("<Microsoft Webhook URL>")
```

With this being a list object, adding the ability to modify a link by index might add complexity and confusion to this otherwise simple module.

It would be fairly simple to add a method to clear the link button list.  Do you have a situation where this would be helpful vs just re-initializing the message?

**Comment by lingwangyan** [comment]
@rveachkc may i know can we check the button is clicked ? 
like function OnClick..

**Comment by lingwangyan** [comment]
If i dont have bots , possible to do that  ? because i am creating a microservice that send a message to Teams... via Webhook.

Thanks
